### ISSUE TITLE
some help

### ISSUE THREAD

**Issue by dkruben** [StranikS-Scan/StranikS_Scan-mods#2]
Hello, can you help me about one thing... how to introduce in one specific mod, code from rating_calcolator
Exemple.
Wn8 = g.calculator(rating=[`wn8`] or im wrong?
I put the link here if possible help me.

https://bitbucket.org/DriftKings/dkmods/src/master/source/scripts/client/gui/mods/mod_BattleEfficiency.py

**Comment by StranikS-Scan** [comment]
Is this a question about my mods? If not, I can not help you.

**Comment by StranikS-Scan** [comment]
If you are interested in how to use the rating_calculation module from my NSM, then look at the examples in this [topic ](https://koreanrandom.com/forum/topic/47960-)on the first page.

**Comment by dkruben** [comment]
Tanks alot...
